### ISSUE TITLE
Variable name clash after SimpleInliner transformation

### ISSUE THREAD

**Issue by mpflanzer** [csmith-project/creduce#112]
I noticed that the SimpleInliner transformation creates invalid test cases when the name of a function parameter already exists in the outer scope into which the function is inlined. For instance the following test case
```
// ---fake_divergence -g 1,1,1 -l 1,1,1
struct S2 {
  int4 g_313;
  char g_350;
};
void func_1(struct S2 *p_886) {
  char *l_349 = &p_886->g_350;
  *l_349 = ((short)p_886->g_313.w >= 6UL);
}
__kernel void entry(__global long *result, int sequence_input) {
  struct S2 c_887;
  struct S2 *p_886 = &c_887;
  struct S2 c_888 = {(int4)-8L};
  c_887 = c_888;
  func_1(p_886);
  result[0] = p_886->g_350;
}
```
is transformed by `clang_delta --transformation=simple-inliner --counter=1 ./test.cl` into:
```
// ---fake_divergence -g 1,1,1 -l 1,1,1
struct S2 {
  int4 g_313;
  char g_350;
};

__kernel void entry(__global long *result, int sequence_input) {
  struct S2 c_887;
  struct S2 *p_886 = &c_887;
  struct S2 c_888 = {(int4)-8L};
  c_887 = c_888;
  {struct S2 *p_886 = p_886;

    char *l_349 = &p_886->g_350;
    *l_349 = ((short)p_886->g_313.w >= 6UL);
  }

  ;
  result[0] = p_886->g_350;
}
```
The variable `p_886` is now declared twice and conflicts. The solution would be to use new temporary variables to replace the function parameters and to rename all occurrences of the function parameters in the inlined/copied function body. For example:
```
// ---fake_divergence -g 1,1,1 -l 1,1,1
struct S2 {
  int4 g_313;
  char g_350;
};

__kernel void entry(__global long *result, int sequence_input) {
  struct S2 c_887;
  struct S2 *p_886 = &c_887;
  struct S2 c_888 = {(int4)-8L};
  c_887 = c_888;
  {struct S2 *__param_p_886 = p_886;

    char *l_349 = &__param_p_886->g_350;
    *l_349 = ((short)__param_p_886->g_313.w >= 6UL);
  }

  ;
  result[0] = p_886->g_350;
}
```

@chenyang78 would that be something you could do quickly without much effort? Otherwise I will take a look.

Another thing that might be useful: Instead of just deleting return statements in the inlined/copied function body they could be replaced with `goto out_1;` and an `out_1:` label could be added to the very end of the inlined/copied function body.

**Comment by regehr** [comment]
Thanks for looking into this Moritz! I have been seeing lots of cases where the inliner should have fired and had been meaning to look into it but hadn't had a chance yet. Inlining is one of those programming jobs that seems super easy but isn't...

**Comment by mpflanzer** [comment]
I had some time and hacked a few bits together: https://github.com/mpflanzer/creduce/commit/1cdf574ca8593cb4d9b428cb88eb69b2c9410a03

Not really nice but it seems to work and does the transformation like I suggested above. Eventually the SimpleInliner needs a bit of cleanup and then I might be time took at the idea with adding label to simulate the return. Problem with that is that the label name has to be unique within the entire test case.

**Comment by chenyang78** [comment]
@mpflanzer Thanks for the quick fix! I will take a look at it tonight.

**Comment by chenyang78** [comment]
@mpflanzer Inspired by your patch, I fixed the issue in a slightly different way. Instead of keeping track of the parameter with conflict and renaming all of its occurrence, the committed fix added another scope where the conflicting argument is assigned to a temporary variable, which is then assigned back to the corresponding "parameter". For example, applying ```./clang_delta --transformation=simple-inliner --counter=1 foo.c``` to the code below

    int printf(const char *format, ...);
    void foo(int *p1, int *p2) {
      *p1 = 11;
      *p2 = 22;
    }
    int main() {
      int x = 0, y = 0;
      int *p1 = &x, *p2 = &y;
      foo(p1, p2);
      printf("%d\n", *p1 + *p2);
      return 0;
    }

gives us something like this (slightly re-formatted):

    int printf(const char *format, ...);
    int main() {
      int x = 0, y = 0;
      int *p1 = &x, *p2 = &y;
      {
      int *__trans_tmp_1 = p1;
      int *__trans_tmp_2 = p2;
      { int *p1 = __trans_tmp_1;
        int *p2 = __trans_tmp_2;
        *p1 = 11;
        *p2 = 22;
      }}  
      ;
      printf("%d\n", *p1 + *p2);
      return 0;
    }

Again, thanks for diagnosing the issue!
