### ISSUE TITLE
ENABLE_TRANS_ASSERT should not be disabled in CMakeLists.txt

### ISSUE THREAD

**Issue by oriceemple** [csmith-project/creduce#116]
ENABLE_TRANS_ASSERT is set to OFF, this causes asserts to exit(0) instead of failing, which causes creduce's pass_cdelta to enter an infinite loop for passes that assert.

**Comment by eeide** [comment]
You're right—this is inconsistent with the Automake-based build path.  Thank you for pointing this out; I will commit a fix.

@chenyang78, can you comment about the infinite-loop issue? Surely, `pass_clang` shouldn't infinite-loop if `ENABLE_TRANS_ASSERT` is set to zero, should it?

**Comment by oriceemple** [comment]
If there is a pass that asserts during its initialization, it will exit(0). The successful exit will cause creduce to increase the counter by 1 and try again, and then assert again, and so on...

**Comment by chenyang78** [comment]
Markus's description is correct. I committed a fix to make clang_delta exit with -1 on failures. Thanks for catching the issue, @oriceemple !
