### ISSUE TITLE
clang_delta/ReplaceFunctionDefWithDecl.cpp:123: double write ?

### ISSUE THREAD

**Issue by dcb314** [csmith-project/creduce#123]
clang_delta/ReplaceFunctionDefWithDecl.cpp:123:1: warning: V519 The 'Loc' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 122, 123.

Source code is

  SourceLocation Loc = RewriteHelper->getLocationFromLeftUntil(LocStart, ':');
  Loc = RewriteHelper->getLocationFromLeftUntil(LocStart, ')');

**Comment by chenyang78** [comment]
Fixed. Thanks for reporting the issue, @dcb314 !
