### ISSUE TITLE
clex/driver.c:444: Pointless test ?

### ISSUE THREAD

**Issue by dcb314** [csmith-project/creduce#124]
clex/driver.c:444:1: warning: V728 An excessive check can be simplified. The '||' operator is surrounded by opposite expressions '!started' and 'started'. 

Source code is

   if (!started || (started && which > (idx + n_toks)))

**Comment by eeide** [comment]
How would you simplify this test?

**Comment by UniQP** [comment]
`if (!started || which > (idx + n_toks))`
