### ISSUE TITLE
llvm trunk patch - disambiguate StringLiteral

### ISSUE THREAD

**Issue by octoploid** [csmith-project/creduce#127]
LLVM now also has a StringLiteral, the following patch is necessary to disambiguate them:

```
 diff --git a/clang_delta/ExpressionDetector.cpp b/clang_delta/ExpressionDetector.cpp
index f84153d45752..be519eb3cada 100644
--- a/clang_delta/ExpressionDetector.cpp
+++ b/clang_delta/ExpressionDetector.cpp
@@ -452,8 +452,8 @@ bool ExpressionDetector::isIdenticalExpr(const Expr *E1, const Expr *E2)
   }

   case Stmt::StringLiteralClass: {
-    const StringLiteral *Lit1 = cast<StringLiteral>(E1);
-    const StringLiteral *Lit2 = cast<StringLiteral>(E2);
+    const clang::StringLiteral *Lit1 = cast<clang::StringLiteral>(E1);
+    const clang::StringLiteral *Lit2 = cast<clang::StringLiteral>(E2);
     return Lit1->getBytes() == Lit2->getBytes();
   }
```

**Comment by eeide** [comment]
Thanks for the patch!

(Unless I am mistaken,) This will need to be applied to an `llvm-svn-compatible` branch in the C-Reduce repo, because we try to keep the `master` branch compatible with the current LLVM release.

**Comment by octoploid** [comment]
I think it should be applied to master, because it obviously works for both LLVM stable and trunk.

**Comment by eeide** [comment]
I'm going to close this issue because there is a pull request (#128) for the same change.
