### ISSUE TITLE
clang_delta crash

### ISSUE THREAD

**Issue by marxin** [csmith-project/creduce#134]
$ cat tmp4u9eanas.ii
struct {
  const int b} a[] = [

$ clang_delta --transformation=empty-struct-to-int --counter=1 tmp4u9eanas.ii 
Segmentation fault (core dumped)

Thanks

**Comment by marxin** [comment]
creduce 2.6.0
b02c375
Linux
marxinbox
4.10.3-1-default
#1 SMP PREEMPT Wed Mar 15 07:47:00 UTC 2017 (0c9f8e4)
x86_64

**Comment by chenyang78** [comment]
I think it has been fixed recently. Thanks for reporting the issue!
