### ISSUE TITLE
creduce pass issue

### ISSUE THREAD

**Issue by marxin** [csmith-project/creduce#135]
creduce 2.6.0
b02c375
Linux
marxinbox
4.10.3-1-default
#1 SMP PREEMPT Wed Mar 15 07:47:00 UTC 2017 (0c9f8e4)
x86_64

***************************************************

pass_clang::rename-cxx-method has encountered a bug:
pass failed to modify the variant

Please consider tarring up /tmp/creduce_bug_000
and mailing it to creduce-bugs@flux.utah.edu and we will try to fix
the bug.

This bug is not fatal, C-Reduce will continue to execute.

***************************************************

```
$ cat tmpvu2iwxks.ii 
struct A {
  int m_fn1();
  void m_fn2() { static int d = m_fn1(); }
};
void fn1() {
  A e;
  e.m_fn2();
}
```

**Comment by marxin** [comment]
And one another test-case:

```
cat tmpod42hc5w.ii 
template < typename c, c > struct d {
         m_fn1({
  d < int, (long)&&b - (long)&&a
```

**Comment by chenyang78** [comment]
Fixed. Thanks for reporting the bug, @marxin !
