### ISSUE TITLE
Reducing help

### ISSUE THREAD

**Issue by Cellule** [csmith-project/creduce#137]
I am trying to reduce a file generated by csmith, but very early creduce remove the `#include "csmith.h"` and even though I indicate it is an invalid step, all the following steps have the include removed

```bash
Request to test step0: failed
===< 31435 >===
running 1 interestingness test in parallel
===< pass_includes :: 0 >===
Request to test step1: failed
(0.0 %, 69080 bytes)
===< pass_unifdef :: 0 >===
===< pass_comments :: 0 >===
Request to test step2: passed
Request to test step3: passed
===< pass_blank :: 0 >===
...
```
`failed` means my bug repro and `passed` means build break (or no repro)
step0 is the initial step to make sure the bug does repro with no change
step1 from the log seems to say it is removing the include, but I make a copy of the file everytime before testing it and the include is present.
all the following steps are missing the include.

I have the same problem with version 2.5.0 (18e04be) and 2.2.1

**Comment by mpflanzer** [comment]
Could you provide the generated file you're trying to reduce and your interestingness test? That would make it easier to reproduce the issue and to check what's going wrong.

**Comment by Cellule** [comment]
You can see the file I am trying to reduce here: https://gist.github.com/Cellule/14506d5e2c1ae8a99d4d8dbe40ca7f2b

My test is a little complicated. I have the logic for build/test in a node.js program
This is the way I invoke creduce is the following
- Run node.js program which figures out how the build/testing will happen
- Start an http server to know when creduce has something for me to test
- Start creduce
  - I create a run.sh script with the following `creduce -n 1 ./test.sh bug.c`
  - Where test.sh is `curl "http://localhost:8080" | grep failed >/dev/null 2>&1`
- When `curl` makes the request, my node server starts a build of bug.c, then runs it in my engine to figure out if the bug still occurs. Then it send `failed` or `passed` back to the requester where 
  - failed: The bug still happens
  - passed: The bug doesn't happen or failed to build

From what I can see while debugging, it looks like when `test.sh` is called after `===< pass_includes :: 0 >===` bug.c hasn't changed and thus I end up testing the previous faulty version and creduce thinks that it's ok to remove the include.
I tested on Windows using Linux subsystem and I tested directly on linux with same result.

**Comment by Cellule** [comment]
Closing since I no longer need to do this
