### ISSUE TITLE
clang_delta: replace-function-def-with-decl doesn't appear to work on methods

### ISSUE THREAD

**Issue by fitzgen** [csmith-project/creduce#145]
I would expect that it would.

For bindgen's reductions, at least, replace-function-def-with-decl has a high interestingness rate, and I suspect that doing the same with methods would also have a high interestingness rate.

**Comment by chenyang78** [comment]
@fitzgen This transformation works with methods. For example, 

    $ cat method.cc 
    struct S {
      void foo() {
      }
    };

    $ ./clang_delta --transformation=replace-function-def-with-decl method.cc --counter=1
    struct S {
      void foo() ;
    };

Perhaps you hit a bug in the transformation or some limitation of it? Can you send us a test? Thanks!

**Comment by fitzgen** [comment]
Huh.

Unfortunately, I overwrote the test case and can't seem to create a test case that reproduces the behavior anymore :(

I was working with a pre-processed file, and specifying both `--counter` and `--to-counger` such that I would remove all method definitions, if that makes a difference.

I realize that this issue is now pretty worthless, so I'll just close it and reopen if I find a test case that does reproduce. Sorry!

**Comment by chenyang78** [comment]
@fitzgen No problem :) Thanks for checking it!
