### ISSUE TITLE
Make C-Reduce release for LLVM/Clang 6.0 (was 5.0)

### ISSUE THREAD

**Issue by eeide** [csmith-project/creduce#147]
Shortly after LLVM 5.0 is officially released, make an official C-Reduce release that uses/requires LLVM 5.0.

**Comment by hmage** [comment]
LLVM 5.0 is out, creduce 2.7.0 fails to compile.

```
c++ -DHAVE_CONFIG_H -I. -I..   -I"/home/hmage/norm.test.x86_64-pc-linux-gnu.2.24.haswell.stretch64/include/clang" -I/home/hmage/norm.test.x86_64-pc-linux-gnu.2.24.haswell.stretch64/include -march=native -I/home/hmage/norm.test.x86_64-pc-linux-gnu.2.24.haswell.stretch64/include -I/home/hmage/norm.test.x86_64-pc-linux-gnu.2.24.haswell.stretch64/include -march=native -fPIC -fvisibility-inlines-hidden -std=c++11 -ffunction-sections -fdata-sections -DNDEBUG -fno-exceptions -fno-rtti -DLLVM_BUILD_GLOBAL_ISEL -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -fno-exceptions -g -O3 -fno-strict-aliasing -Wall -Wextra -Wno-long-long -Wno-unused-parameter -Wno-missing-field-initializers -c -o clang_delta-TransformationManager.o `test -f 'TransformationManager.cpp' || echo './'`TransformationManager.cpp
TransformationManager.cpp: In member function 'bool TransformationManager::initializeCompilerInstance(std::__cxx11::string&)':
TransformationManager.cpp:104:14: error: 'IK_C' was not declared in this scope
   if ((IK == IK_C) || (IK == IK_PreprocessedC)) {
              ^~~~
TransformationManager.cpp:104:30: error: 'IK_PreprocessedC' was not declared in this scope
   if ((IK == IK_C) || (IK == IK_PreprocessedC)) {
                              ^~~~~~~~~~~~~~~~
TransformationManager.cpp:107:19: error: 'IK_CXX' was not declared in this scope
   else if ((IK == IK_CXX) || (IK == IK_PreprocessedCXX)) {
                   ^~~~~~
TransformationManager.cpp:107:37: error: 'IK_PreprocessedCXX' was not declared in this scope
   else if ((IK == IK_CXX) || (IK == IK_PreprocessedCXX)) {
                                     ^~~~~~~~~~~~~~~~~~
TransformationManager.cpp:113:17: error: 'IK_OpenCL' was not declared in this scope
   else if(IK == IK_OpenCL) {
                 ^~~~~~~~~
Makefile:1831: recipe for target 'clang_delta-TransformationManager.o' failed
```

**Comment by eeide** [comment]
@hmage Thanks. If you want to use C-Reduce with LLVM 5.0 before we make a new C-Reduce release, try using the code on C-Reduce's `llvm-svn-compatible` branch.

**Comment by mgorny** [comment]
Ping. We're already past LLVM 6.0.0 release, and it looks like we aren't going to see any 5.0.0-compatible release…

**Comment by eeide** [comment]
I am working to make a new release. Thank you for the reminder and for your patience.

**Comment by ismail** [comment]
Would also appreciate llvm 6.0 support for openSUSE.

**Comment by eeide** [comment]
Hi, @ismail.

I don't have access to an openSUSE machine to test with. Can you tell me if the current git version of C-Reduce (commit 48e622b) builds and runs correctly on openSUSE?

**Comment by eeide** [comment]
I'm guessing that the output you included is from the Automake-based build system. Is that right?

Does the CMake-based build system work?

**Comment by eeide** [comment]
Thanks for checking.

(I'm very surprised that the CMake-based system would fail and the Automake-based system would work! The CMake-based system reuses some of LLVM's build infrastructure, whereas the Automake-based system has to make "informed guesses.")

**Comment by ismail** [comment]
I don't have a shared library setup to test but the following fixes the problem for me.

[p.txt](https://github.com/csmith-project/creduce/files/1954539/p.txt)

**Comment by mgorny** [comment]
I think you also want to account for the switch controlling dylib build.

That said, i think there was a patch that might be somewhat related being discussed at some point. However, I don't recall if it actually addressed the same issue, and what was its state, and I can't find it now (probably lost in mail cleanup).

**Comment by eeide** [comment]
I made the LLVM-6.0-compatible release of C-Reduce on July 7, 2018: 91bdbda.

I'm closing this issue, but some of the linking troubles mentioned above seem to linger. They will have to be remembered in separate issues (e.g., issue #165).
