### ISSUE TITLE
clang_delta: Segfault in param-to-global transformation

### ISSUE THREAD

**Issue by UniQP** [csmith-project/creduce#148]
I have the following test file
[test.c](https://github.com/csmith-project/creduce/files/1285141/test.txt)

```
void f(x, y) int x;
{}
```
that segfaults during the param-to-global transformation:
```
clang_delta --transformation=param-to-global --counter=1 test.c
Segmentation fault (core dumped)
```

I'm not using the latest version of creduce, but maybe the bug is also present on `master`.
```
clang_delta --version          
clang_delta 2.6.0
Git version: b02c375
```

**Comment by chenyang78** [comment]
Fixed. Thanks for reporting the issue, @UniQP !
