### ISSUE TITLE
pass_clang_binsrch::remove-unused-var has encountered a bug

### ISSUE THREAD

**Issue by sgraf812** [csmith-project/creduce#151]
Hey,

I attached a [reproduction](bug.tar.gz) that caused a crash while minimizing some example. Hope it helps!

[bug.tar.gz](https://github.com/csmith-project/creduce/files/1551735/bug.tar.gz)

**Comment by eeide** [comment]
Thank you for your report!

**Comment by chenyang78** [comment]
Fixed. Thanks for the report, @sgraf812 !
