### ISSUE TITLE
Can we bin automake?

### ISSUE THREAD

**Issue by pranavk** [csmith-project/creduce#158]
I am wondering why creduce is using two build systems? Since we have cmake, we can get rid of autotools, I guess. Or is there some reason we still have autotools?

**Comment by eeide** [comment]
Is the support for Automake causing you a problem?

**Comment by pranavk** [comment]
No, not causing any problem. But since cmake can do autotools job anyways, why keep autotools at all?

**Comment by eeide** [comment]
I maintain the Automake-based build path for the convenience of people who want to use it, and I use it myself for some tasks, such as making the official release tarballs.

Thanks for the clarification.
