### ISSUE TITLE
`clang_delta` link gets stuck on macOS w/Autoconf-based build path

### ISSUE THREAD

**Issue by eeide** [csmith-project/creduce#162]
_This issue is really a "note to self" to investigate something that I don't want to investigate now._

At the current master HEAD (5bf8445).

On macOS 10.12.6 (Sierra), with an LLVM 6.0 tree built from source, if I build C-Reduce using the Autoconf-based build system, the build gets stuck trying to link `clang_delta`.

If I use the CMake-based build path, the link step completes.

I haven't investigated the differences between the link command lines on the two paths.

This ultimately might not be worth fixing, either because an OS update fixes it, or because I give up on maintaining the Autoconf-based build path, or...

**Comment by regehr** [comment]
On my Mac (with LLVM 6 downloaded binary) I see the same thing: ld 
hanging up using 100% of a core. I'll leave it running a while and see 
if it finishes but it's been a few minutes already.

I see no reason to keep supporting the autoconf tooling when LLVM itself 
has deprecated it a while ago.

John

**Comment by eeide** [comment]
I use the Autoconf-based build system for making the distributions.

Anyway, there are some things to "port" from the Autoconf-based build path before we dispose of it.

**Comment by eeide** [comment]
Aside, shout out to issue #158.

**Comment by eeide** [comment]
As of C-Reduce 2.9.0 (which uses LLVM 7), I am no longer seeing the gets-stuck-on-link behavior on macOS.

For that reason, I am closing this issue.
