### ISSUE TITLE
creduce-2.8.0 fails to compile wirth GCC 8.2.0 and LLVM 7.0

### ISSUE THREAD

**Issue by hauihau** [csmith-project/creduce#173]
The above combinatiion leads to:

`
[10/88] /usr/bin/x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I/home/gentoo/tmp/portage/dev-util/creduce-2.8.0_pre20180411/work/creduce-48e622ba74bc35c5a81299d3a34b9b14038d6a70/clang_delta -I/usr/lib/llvm/7/include  -DNDEBUG -march=native -O3 -pipe -flto=5 -fuse-linker-plugin -fno-delete-null-pointer-checks -flifetime-dse=1 -std=c++11 -fno-rtti -fno-strict-aliasing -Wall -Wextra -Wno-long-long -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility-inlines-hidden   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -MD -MT clang_delta/CMakeFiles/clang_delta.dir/ExpressionDetector.cpp.o -MF clang_delta/CMakeFiles/clang_delta.dir/ExpressionDetector.cpp.o.d -o clang_delta/CMakeFiles/clang_delta.dir/ExpressionDetector.cpp.o -c /home/gentoo/tmp/portage/dev-util/creduce-2.8.0_pre20180411/work/creduce-48e622ba74bc35c5a81299d3a34b9b14038d6a70/clang_delta/ExpressionDetector.cpp
FAILED: clang_delta/CMakeFiles/clang_delta.dir/ExpressionDetector.cpp.o
/usr/bin/x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I/home/gentoo/tmp/portage/dev-util/creduce-2.8.0_pre20180411/work/creduce-48e622ba74bc35c5a81299d3a34b9b14038d6a70/clang_delta -I/usr/lib/llvm/7/include  -DNDEBUG -march=native -O3 -pipe -flto=5 -fuse-linker-plugin -fno-delete-null-pointer-checks -flifetime-dse=1 -std=c++11 -fno-rtti -fno-strict-aliasing -Wall -Wextra -Wno-long-long -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility-inlines-hidden   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -MD -MT clang_delta/CMakeFiles/clang_delta.dir/ExpressionDetector.cpp.o -MF clang_delta/CMakeFiles/clang_delta.dir/ExpressionDetector.cpp.o.d -o clang_delta/CMakeFiles/clang_delta.dir/ExpressionDetector.cpp.o -c /home/gentoo/tmp/portage/dev-util/creduce-2.8.0_pre20180411/work/creduce-48e622ba74bc35c5a81299d3a34b9b14038d6a70/clang_delta/ExpressionDetector.cpp
In file included from /usr/lib/llvm/7/include/clang/AST/RecursiveASTVisitor.h:24,
                 from /home/gentoo/tmp/portage/dev-util/creduce-2.8.0_pre20180411/work/creduce-48e622ba74bc35c5a81299d3a34b9b14038d6a70/clang_delta/ExpressionDetector.cpp:17:
/usr/lib/llvm/7/include/clang/AST/DeclOpenMP.h:97:1: warning: multi-line comment [-Wcomment]
 /// #pragma omp declare reduction (foo : int,float : omp_out += omp_in) \
 ^
/home/gentoo/tmp/portage/dev-util/creduce-2.8.0_pre20180411/work/creduce-48e622ba74bc35c5a81299d3a34b9b14038d6a70/clang_delta/ExpressionDetector.cpp:62:8: error: ‘void {anonymous}::IncludesPPCallbacks::InclusionDirective(clang::SourceLocation, const clang::Token&, llvm::StringRef, bool, clang::CharSourceRange, const clang::FileEntry*, llvm::StringRef, llvm::StringRef, const clang::Module*)’ marked ‘override’, but does not override
   void InclusionDirective(SourceLocation HashLoc, const Token &IncludeTok,
        ^~~~~~~~~~~~~~~~~~
In file included from /usr/lib/llvm/7/include/llvm/ADT/STLExtras.h:21,
                 from /usr/lib/llvm/7/include/llvm/ADT/StringRef.h:13,
                 from /usr/lib/llvm/7/include/llvm/ADT/StringMap.h:17,
                 from /usr/lib/llvm/7/include/llvm/Support/Host.h:17,
                 from /usr/lib/llvm/7/include/llvm/ADT/Hashing.h:49,
                 from /usr/lib/llvm/7/include/llvm/ADT/ArrayRef.h:13,
                 from /usr/lib/llvm/7/include/llvm/ADT/DenseMapInfo.h:17,
                 from /usr/lib/llvm/7/include/llvm/ADT/DenseMap.h:17,
                 from /home/gentoo/tmp/portage/dev-util/creduce-2.8.0_pre20180411/work/creduce-48e622ba74bc35c5a81299d3a34b9b14038d6a70/clang_delta/ExpressionDetector.h:16,
                 from /home/gentoo/tmp/portage/dev-util/creduce-2.8.0_pre20180411/work/creduce-48e622ba74bc35c5a81299d3a34b9b14038d6a70/clang_delta/ExpressionDetector.cpp:15:
/usr/lib/llvm/7/include/llvm/ADT/SmallVector.h: In instantiation of ‘void llvm::SmallVectorTemplateBase<T, true>::push_back(const T&) [with T = std::pair<void*, long unsigned int>]’:
/usr/lib/llvm/7/include/llvm/Support/Allocator.h:249:33:   required from ‘void* llvm::BumpPtrAllocatorImpl<AllocatorT, SlabSize, SizeThreshold>::Allocate(size_t, size_t) [with AllocatorT = llvm::MallocAllocator; long unsigned int SlabSize = 4096; long unsigned int SizeThreshold = 4096; size_t = long unsigned int]’
/usr/lib/llvm/7/include/clang/AST/ASTContext.h:659:42:   required from here
/usr/lib/llvm/7/include/llvm/ADT/SmallVector.h:313:11: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct std::pair<void*, long unsigned int>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
     memcpy(this->end(), &Elt, sizeof(T));
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_algobase.h:64,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/vector:60,
                 from /home/gentoo/tmp/portage/dev-util/creduce-2.8.0_pre20180411/work/creduce-48e622ba74bc35c5a81299d3a34b9b14038d6a70/clang_delta/ExpressionDetector.h:14,
                 from /home/gentoo/tmp/portage/dev-util/creduce-2.8.0_pre20180411/work/creduce-48e622ba74bc35c5a81299d3a34b9b14038d6a70/clang_delta/ExpressionDetector.cpp:15:
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_pair.h:198:12: note: ‘struct std::pair<void*, long unsigned int>’ declared here
     struct pair
            ^~~~
/home/gentoo/tmp/portage/dev-util/creduce-2.8.0_pre20180411/work/creduce-48e622ba74bc35c5a81299d3a34b9b14038d6a70/clang_delta/ExpressionDetector.cpp:78:6: warning: ‘void {anonymous}::IncludesPPCallbacks::InclusionDirective(clang::SourceLocation, const clang::Token&, llvm::StringRef, bool, clang::CharSourceRange, const clang::FileEntry*, llvm::StringRef, llvm::StringRef, const clang::Module*)’ defined but not used [-Wunused-function]
 void IncludesPPCallbacks::InclusionDirective(SourceLocation HashLoc,
      ^~~~~~~~~~~~~~~~~~~
`

Haven't found any similar issues so I decided to report this here. Any fix is appreciated.

**Comment by eeide** [comment]
Is compiling with LLVM 7.0 an option for you?

(That is, rather than compile C-Reduce with GCC, compile C-Reduce with clang from the LLVM 7.0 distribution.)

I realize that this is not a direct answer to your question. But if your real goal is to compile C-Reduce, maybe compiling with LLVM is an option for you?

**Comment by eeide** [comment]
The general problem of compiling with GCC is briefly addressed in the `INSTALL` file.

```
* Preface: If in Doubt, Compile With `clang++'
```

**Comment by hauihau** [comment]
Does not help:

`
[10/88] /usr/lib/llvm/7/bin/x86_64-pc-linux-gnu-clang++ -DHAVE_CONFIG_H -I. -I../clang_delta -I/usr/lib/llvm/7/include  -DNDEBUG -std=c++11 -fno-rtti -fno-strict-aliasing -Wall -Wextra -Wno-long-long -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility-inlines-hidden   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -MD -MT clang_delta/CMakeFiles/clang_delta.dir/ExpressionDetector.cpp.o -MF clang_delta/CMakeFiles/clang_delta.dir/ExpressionDetector.cpp.o.d -o clang_delta/CMakeFiles/clang_delta.dir/ExpressionDetector.cpp.o -c ../clang_delta/ExpressionDetector.cpp
FAILED: clang_delta/CMakeFiles/clang_delta.dir/ExpressionDetector.cpp.o 
/usr/lib/llvm/7/bin/x86_64-pc-linux-gnu-clang++ -DHAVE_CONFIG_H -I. -I../clang_delta -I/usr/lib/llvm/7/include  -DNDEBUG -std=c++11 -fno-rtti -fno-strict-aliasing -Wall -Wextra -Wno-long-long -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility-inlines-hidden   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -MD -MT clang_delta/CMakeFiles/clang_delta.dir/ExpressionDetector.cpp.o -MF clang_delta/CMakeFiles/clang_delta.dir/ExpressionDetector.cpp.o.d -o clang_delta/CMakeFiles/clang_delta.dir/ExpressionDetector.cpp.o -c ../clang_delta/ExpressionDetector.cpp
../clang_delta/ExpressionDetector.cpp:66:51: error: non-virtual member function marked 'override' hides virtual member function
                          const Module *Imported) override;
                                                  ^
/usr/lib/llvm/7/include/clang/Lex/PPCallbacks.h:124:16: note: hidden overloaded virtual function 'clang::PPCallbacks::InclusionDirective' declared here: different number of parameters (10 vs 9)
  virtual void InclusionDirective(SourceLocation HashLoc,
               ^
1 error generated.
ninja: build stopped: subcommand failed.
`


GCC worked perfectly find until my Gentoo system got an update of LLVM from fro 6.0 to 7.0.

**Comment by chenyang78** [comment]
I will take a look at it. Thanks.

**Comment by chenyang78** [comment]
@hauihau Thanks for checking it and sorry about that. The failure was introduced by some API difference in between LLVM 6.0 and 7.0. 

I fixed the issue (along with a couple of others) in a new branch llvm-7.0:

    https://github.com/csmith-project/creduce/tree/llvm-7.0

We will merge the fix to the master branch for our next release. Thanks for reporting the issue!

**Comment by hauihau** [comment]
I justed fetched the single commit from llvm-7.0 branch and this solves the issue  for GCC as well as CLANG.

**Comment by chenyang78** [comment]
@hauihau Thanks for verifying the fix!
