### ISSUE TITLE
Make C-Reduce release for LLVM/Clang 8.0

### ISSUE THREAD

**Issue by ydroneaud** [csmith-project/creduce#191]
On Fedora 30, c-reduce doesn't compile due to multiple changes in LLVM/Clang APIs.

**Comment by eeide** [comment]
Yes, we will make a release that is compatible with LLVM 8.0.

**Comment by eeide** [comment]
As of commit cd45699 (master branch), C-Reduce works with and requires LLVM 8.

@ydroneaud, please try it out and let us know if it works for you. *Thanks!*

**Comment by ydroneaud** [comment]
> @ydroneaud, please try it out and let us know if it works for you. _Thanks!_

Thanks, it compiles now just fine on Fedora 30.

Regards.

**Comment by eeide** [comment]
C-Reduce 2.10.0, just released, supports and requires LLVM 8.

Get it here: https://github.com/csmith-project/creduce/releases/tag/creduce-2.10.0
