### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [csmith-project/creduce#208]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [RenameParam](https://github.com/csmith-project/creduce/blob/9b54272f9f7d6b0d7f4289454d20a847ca97c450/clang_delta/RenameParam.cpp#L272 "Destructor for RenameParam")
- [ReplaceUndefinedFunction](https://github.com/csmith-project/creduce/blob/d67ec8d4f35f05195d49e622609dda4dde50655b/clang_delta/ReplaceUndefinedFunction.cpp#L177 "Destructor for ReplaceUndefinedFunction")
- [TransformationManager::Finalize](https://github.com/csmith-project/creduce/blob/c67e81809a88f63136de27c9725249b8d0cf9cf9/clang_delta/TransformationManager.cpp#L210 "TransformationManager::Finalize function")

**Comment by chenyang78** [comment]
I borrowed the fix in the commit 2dd5d02 made by @marxin to cvise. Thanks!

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/csmith-project/creduce/commit/893dacdf85ea2058fc5de22f927358b16120f731 "Deletion of a few unnecessary checks").

**Comment by chenyang78** [comment]
Thanks for reporting the issue, @elfring !
