### ISSUE TITLE
RewriteUtils.cpp:1080: void RewriteUtils::getStringBetweenLocs(std::string&, clang::SourceLocation, clang::SourceLocation): Assertion `StartBuf < EndBuf' failed.

### ISSUE THREAD

**Issue by marxin** [csmith-project/creduce#214]
I see the following crash:

$ ./clang_delta/clang_delta --transformation=simplify-recursive-template-instantiation --counter=1 crash1.C
[crash1.C.txt](https://github.com/csmith-project/creduce/files/4605573/crash1.C.txt)

Note that file is a valid C++ code:
$ g++ crash1.C -c

**Comment by chenyang78** [comment]
Fixed in d569146. Thanks!
