### ISSUE TITLE
undefined reference after creduce

### ISSUE THREAD

**Issue by yansendao** [csmith-project/creduce#222]
![image](https://user-images.githubusercontent.com/36258307/87266269-6d6c4600-c4f7-11ea-86a7-d8268733bbb1.png)

compile error message beforce creduce:

```
 gcc -O3 -ffinite-loops -I/home/yansendao/software/csmith/include/csmith-2.4.0 -w orig.c                         
during GIMPLE pass: vect
orig.c: In function ‘func_1’:
orig.c:122:17: internal compiler error: in compute_live_loop_exits, at tree-ssa-loop-manip.c:229
  122 | static int32_t  func_1(void)
      |                 ^~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
```

compile error message after creduce:
```
$ gcc -O3 -ffinite-loops -I/home/yansendao/software/csmith/include/csmith-2.4.0 -w issue244-2.c 
/home/yansendao/software/hcc/hcc_arm64le_native/bin/../lib64/gcc/aarch64-target-linux-gnu/9.3.1/../../../../aarch64-target-linux-gnu/bin/ld: /tmp/ccWqBgyF.o: in function `c':
issue244-2.c:(.text+0x4): undefined reference to `f'
collect2: error: ld returned 1 exit status
```

```c
$ cat issue244-2.c 
#include "csmith.h"
a;
b;
int8_t *d(uint16_t, int8_t *, uint32_t, int32_t, uint8_t);
c() {
  int8_t e;
  f(d(b, e, f, a, b));
}
int8_t *d(uint16_t g, int8_t *h, uint32_t i, int32_t l, uint8_t j) {
  uint32_t k;
  for (; k;)
    for (; k <= 6; k++)
      ;
}
main() {}
```

creduce.sh 
```bash
#!/bin/bash
gcc -O3 -I/home/yansendao/software/csmith/include/csmith-2.4.0 test.c -w && ! gcc -O3 -ffinite-loops -I/home/yansendao/software/csmith/include/csmith-2.4.0 test.c -w
```

**Comment by yansendao** [comment]
$ creduce --version
creduce 2.10.0 (fb91843)

**Comment by eeide** [comment]
Your "interestingness test" (`creduce.sh`) checks that `gcc` succeeds with one set of command-line options and fails with another set of command-line options. This effectively gives C-Reduce permission to do a lot of things, some of which you probably don't want it to do. In particular, it has license to find new programs that do not trigger the original bug!

Probably, what you want is to add more conditions to your interestingness test script.

E.g., expand the test script to also check that the error message from  `gcc -O3 -ffinite-loops` contains the string:
`"internal compiler error: in compute_live_loop_exits, at tree-ssa-loop-manip.c:229"`

**Comment by regehr** [comment]
closing, feel free to reopen if Eric did not fully answer the question here
