### ISSUE TITLE
LLVM/Clang 11: creduce fails to build

### ISSUE THREAD

**Issue by berolinux** [csmith-project/creduce#223]
creduce fails to build with LLVM/Clang 11, mostly because implicit casting from LLVM::StringRef to std::string has been removed.
Given you likely want to open a new branch for LLVM 11, I'm linking to the
[patch](https://github.com/OpenMandrivaAssociation/creduce/blob/master/creduce-2.10.0-llvm-11.patch) I've added to the [OpenMandriva](https://openmandriva.org/) [package](https://github.com/OpenMandrivaAssocation/creduce) here rather than sending a pull request.

**Comment by berolinux** [comment]
The patch is meant to be applied on top of the llvm 10 branch -- all the changes to make 10 work are still required for 11.

**Comment by marxin** [comment]
Can you please make a pull request to marxin/cvice repository. I would like to merge it..

**Comment by chenyang78** [comment]
@berolinux Sorry for being late. LLVM 11.0.0 was out the other day. I've created a branch llvm-11.0 that is compatible with the LLVM 11 release. Thanks for sharing the patch with us!
