### ISSUE TITLE
Provide self-contained, static version for download

### ISSUE THREAD

**Issue by octoploid** [csmith-project/creduce#44]
On irc/oftc #gcc people frequently ask for a static,
self-contained build of creduce, with no external dependencies.

So it would be great if at least an x86_64 version would be
available somewhere. 

(I've build a static version on POWER8 by hand today, and it was
a lot of work unfortunately.)

Thanks.

**Comment by UnixJunkie** [comment]
That would be pretty useful for users.
I am also currently fighting to get creduce compiled on my machine.

**Comment by UnixJunkie** [comment]
Also, provinding packages for Ubuntu/Debian would be nice.

**Comment by regehr** [comment]
While I feed bad for not working on this, I'll note that C-Reduce is available from homebrew and also from Ubuntu 14.04, 14.10, and 15.04. Consequently, my motivation is pretty low. Can anyone think of a good reason why we can't just close this and trust the OS packagers to do a decent job here?

**Comment by UnixJunkie** [comment]
Yes, you can close I think.
