### ISSUE TITLE
Test case not completely minimized

### ISSUE THREAD

**Issue by ehsan** [csmith-project/creduce#46]
I used creduce to minimize a large test case to the following code:

```
class A {
public:
  A(bool);
};
template <class Base> class __declspec(dllexport) SecurityWrapper : A {
  constexpr SecurityWrapper() : Base(true) {}
};

template class SecurityWrapper<A>;
```

But a smaller test case is:

```
template <class> struct S {
  constexpr S() {}
};
template class __declspec(dllexport) S<void>;
```

I'm not sure if this is a limitation of creduce that it could not reduce the test case further, but filing this anyway.

**Comment by regehr** [comment]
Closing since I can't reproduce anymore, sorry! In general I want us to fix this sort of thing.
