### ISSUE TITLE
llvm-config-3.5 command instead of llvm-config in the configure file

### ISSUE THREAD

**Issue by UnixJunkie** [csmith-project/creduce#49]
At least on Ubuntu 14.04.1 LTS that seems needed.

**Comment by UnixJunkie** [comment]
libedit-dev was also missing in the list of packages to install for Ubuntu

**Comment by UnixJunkie** [comment]
package libclang-3.5-dev also, but this one was detected missing at compile time, not at configure time

**Comment by UnixJunkie** [comment]
Still not compiling:

    RemoveUnusedFunction.cpp:657:8: warning: ‘auto’ changes meaning in C++11; please remove it 
    [-Wc++0x-compat]

**Comment by UnixJunkie** [comment]
What is the correction to remove the auto keyword from here:

    for (auto *I : Ctx->using_directives()) {

**Comment by UnixJunkie** [comment]
@pippijn any idea from someone near my timezone? ;)

**Comment by regehr** [comment]
Hi Francois, as the INSTALL file suggests, you should download the LLVM binary tarball instead of using the Ubuntu package. Please give that a try and let us know if it doesn't work for you. The INSTALL file also mentions libedit-dev in around the same place.

**Comment by pippijn** [comment]
Without testing, my guess would be:
`for (clang::UsingDirectiveDecl *I : Ctx->using_directives()) {`

**Comment by pippijn** [comment]
But that's a warning, so why doesn't it compile?

**Comment by regehr** [comment]
I can't tell you guys what to do, but I would like to suggest getting the dependencies right rather than hacking the code.

**Comment by eeide** [comment]
Thank you for reporting this issue! I will investigate updates to the configure scripts.

**Comment by UnixJunkie** [comment]
OK, I'll give a try at the llvm binary tarball, since I have an allergy to C++. :)

**Comment by regehr** [comment]
So do we.

**Comment by UnixJunkie** [comment]
You may disregard what I said earlier for the configure file since llvm-config-3.5 is not the command provided by the clang+llvm binary tarball that you suggest to use instead of the system-wide packages

**Comment by pippijn** [comment]
Re: allergy: https://paste.xinu.at/AW9rrW/cpp

**Comment by UnixJunkie** [comment]
I had almost forgotten how much C++ takes time to compile ...

**Comment by UnixJunkie** [comment]
I could compile !!! thanks for the help in here.
Now I will try to use creduce productively. :)

**Comment by UnixJunkie** [comment]
As said in another thread, providing binary creduce packages for users would help.
I guess that's why the LLVM people do it.
