### ISSUE TITLE
single threaded multidelta faster than parallel pass_lines pass

### ISSUE THREAD

**Issue by octoploid** [csmith-project/creduce#52]
Running multidelta on a testcase is often much faster than
the pass_lines pass that runs in parallel in creduce.

(Jakub Jelinek claimed this on IRC, and at first I could not believe it.
But my measurements confirmed this.)

**Comment by regehr** [comment]
One possibility is that delta starts at the back of the file and (IIRC) C-Reduce's line pass starts at the front. I tried it both ways and didn't see much of a difference, but of course I might have been looking at the wrong test cases.

Please hack your C-Reduce slightly by setting the $BACKWARD variable in pass_lines.pm to true, and let us know if that makes a difference. (I hope backwards mode still works-- I haven't tried it for a long time.)

If that doesn't make a difference, you'll need to give us a complete testcase to work from.

**Comment by octoploid** [comment]
I always set "my $BACKWARD = 1;" in creduce/pass_lines.pm.
So that probably doesn't make any difference. 

One example is the testcase I'm currently trying to reduce:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65588

    % wget trippelsdorf.de/testcase.tar.bz2

**Comment by octoploid** [comment]
Sorry, I've posted the wrong gcc bug link. This one is correct:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65549

**Comment by octoploid** [comment]
Although in this particular case -flto=8 might slow down creduce's
parallel execution (on an 8 core machine). 
But any big (say >6MB) testcase should demonstrate the issue.

**Comment by regehr** [comment]
Thanks Markus, I'll look into this when I get time. There doesn't seem to be any reason why C-Reduce should be systematically slower than multidelta.

Note that there's a big element of getting lucky in testcase reduction, we've noticed this when comparing multiple C-Reduce versions. Sometimes one version will be better than the previous release for most inputs but there are almost always some cases where the worse version will do much better just because it happens to eliminate 50% of the testcast in one shot.

**Comment by regehr** [comment]
Yeah the first thing I would do when comparing delta vs. C-Reduce is to turn off parallel mode.

**Comment by regehr** [comment]
Markus please also send the multidelta commands you are using.

**Comment by octoploid** [comment]
multidelta -level=0 ./check.sh tcp_client.ii
v.s
    creduce ./check.sh tcp_client.ii 
(replace-function-def-with-decl and remove-unused-function will crash, so creduce starts with
"pass_lines 0".)

**Comment by regehr** [comment]
Just a note that I'm back to spending some time on C-Reduce lately and will take a look at this issue soonish.

**Comment by regehr** [comment]
I'm pretty sure I've found a nasty bug in C-Reduce's line delta, which is silly since I had long considered it debugged. I'll be fixing it soon. It's not 100% clear that it's the reason why C-Reduce is slower than delta but it's certainly not helpful.

**Comment by regehr** [comment]
Besides bugs there are two reasons why delta might be faster. First, they may have happened to chose a chunk reduction policy that is better. Second, their reducer remembers a lot more about the test case in between transformations. Their code is a bit painful.  C-Reduce's line delta is far simpler but the cost is that it has to recompute things that it could have remembered.

**Comment by regehr** [comment]
Markus and I have been discussing this issue in email but I thought I'd move the discussion back here before closing this issue.

For the testcase and command line above, delta requires 2:41 to create a 669 KB file. C-Reduce, using the line-pass-rewrite branch, in a similar configuration (three runs of pass_lines with topformflat=0, and no other passes) requires 1:59 to produce a 159 KB file.

Why is C-Reduce doing better? Basically it got a lucky break. It was stuck at around 700 KB and then eliminated a big chunk of the remaining file. Other times this will not happen, but as far as I can tell even in that case C-Reduce should not be drastically slower than delta. Anyway I plan to close this and merge the branch.

**Comment by regehr** [comment]
The 1:59 time above is for C-Reduce using just one core.

**Comment by regehr** [comment]
Closing-- thanks for reporting this @octoploid
