### ISSUE TITLE
Release a version that supports LLVM 3.6

### ISSUE THREAD

**Issue by tamird** [csmith-project/creduce#53]
The latest release, 2.2.1, fails with LLVM 3.6 with:
```
/usr/local/Cellar/creduce/2.2.1/bin/creduce test1.sh test1.c
prereqs not found for pass pass_indent at /usr/local/Cellar/creduce/2.2.1/libexec/creduce line 238.
```

See:
https://github.com/Homebrew/homebrew/pull/37260#issuecomment-97947784
http://bot.brew.sh/job/Homebrew%20Pull%20Requests/25183/version=mavericks/console
http://bot.brew.sh/job/Homebrew%20Pull%20Requests/25183/version=yosemite/console

Looks like master also fails to compile against LLVM 3.6: https://gist.github.com/tamird/881e2bf7f2b920084fa7

**Comment by regehr** [comment]
I've updated the master branch so that it compiles against LLVM 3.6. I don't have a Mac at the moment so I've only tested on Ubuntu. Please check on your Mac, tamird.

**Comment by regehr** [comment]
tamird, you additionally do not appear to have any of the required perl modules installed. Please see our INSTALL file for a full list of dependencies.

checking for perl module Benchmark::Timer... no
checking for perl module Exporter::Lite... no
checking for perl module File::Which... ok
checking for perl module Getopt::Tabular... no
checking for perl module Regexp::Common... ok
checking for perl module Sys::CPU... no

**Comment by tamird** [comment]
Yeah, the perl module are installed in a special place. Anyway, this works! Let's release it :)

**Comment by regehr** [comment]
Eric, can you do a 2.2.2 release? I think all that is required is a very minor update to INSTALL.

**Comment by tamird** [comment]
@eeide ^

**Comment by eeide** [comment]
John Regehr <notifications@github.com> writes:

> Eric, can you do a 2.2.2 release? I think all that is required is a very minor
> update to INSTALL.

Sure, I will do this --- but I am likely to call it 2.3.  That would be more in
keeping with the version-management scheme that we have.

Eric.

-- 
-------------------------------------------------------------------------------
Eric Eide <eeide@cs.utah.edu>  .         University of Utah School of Computing
http://www.cs.utah.edu/~eeide/ . +1 (801) 585-5512 voice, +1 (801) 581-5843 FAX

**Comment by tamird** [comment]
@eeide any progress on this? homebrew's update to LLVM 3.6 is blocked on this at the moment.

**Comment by eeide** [comment]
I still need to test the current version. I will be able to do this later this week; I am traveling now. You can help by testing it, too.

**Comment by tamird** [comment]
I set up a minimal CI here: https://github.com/csmith-project/creduce/pull/54

**Comment by eeide** [comment]
Done! See tag creduce-2.3.0

**Comment by DomT4** [comment]
May need a new release again. Same failure this time around for the `3.6.1` LLVM release a few days ago.

```
prereqs not found for pass pass_indent at /usr/local/Cellar/creduce/2.3.0/libexec/creduce line 238.
Error: creduce: failed
```

**Comment by eeide** [comment]
Thanks! We aim to keep the master branch of C-Reduce is sync with the current released version of LLVM. I'll investigate what needs to be done to C-Reduce for compatibility with LLVM 3.6.1.

@DomT4: At first glance, the behavior that you are reporting sounds like a Homebrew packaging issue, not a problem with C-Reduce's implementation w.r.t. LLVM 3.6.1. I could be wrong about that, though.

**Comment by DomT4** [comment]
> @DomT4: At first glance, the behavior that you are reporting sounds like a Homebrew packaging issue, not a problem with C-Reduce's implementation w.r.t. LLVM 3.6.1. I could be wrong about that, though.

Thanks. I'll bump the package and force it to build from source. It could be that the binary we produce has the expected LLVM version hardcoded in somewhere.

**Comment by DomT4** [comment]
Yeah, that was it. I'd presume that part of the `prereqs` is a hardcoded LLVM version linked to `creduce`?

**Comment by eeide** [comment]
I guess so. Let me preface the rest of this answer by saying that I don't install LLVM or C-Reduce via Homebrew, so anything I say about how those things are packaged might be wrong.

One of the tools in C-Reduce, "clang_delta", links against internal LLVM libraries. It locates these libraries and figures out how to link to them by invoking LLVM's "llvm-config" tool. We link against the shared libraries, so they become run-time dependencies of the "clang_delta" tool (and thus, C-Reduce).

My guess is that Homebrew packages LLVM in a way that causes the internal libraries to move, or at least be renamed, between releases of LLVM. I don't know this for certain, but it would explain why C-Reduce wouldn't work after one updates LLVM via Homebrew.

We (the C-Reduce authors) have not thought at all about how to allow LLVM to be upgraded "out from under" C-Reduce, while allowing C-Reduce to continue to work. If there are things we could do to better support this, I'd like to know—but I suspect it might be tricky and fragile. With respect to Homebrew, it might be easier and more reliable to simply declare that particular versions of the C-Reduce package depend on particular versions of the LLVM package.

We (the C-Reduce authors) *have* thought some about making C-Reduce be more stand-alone—basically, statically linking against its various dependencies at build time. We started some experimental work toward this, but it is not yet complete. If/when it is finished, it would solve the run-time dependency issue that you reported, and possibly make it easier for people to use C-Reduce in general.
