### ISSUE TITLE
Error in clang_delta Makefiles

### ISSUE THREAD

**Issue by mpflanzer** [csmith-project/creduce#56]
The latest commit (96e284096a98c67ec5af8d70837b059825500183) introduced two mistakes in the Makefile.am and Makefile.in in clang_delta. After each change there is a backtick (`) too much and causes parsing errors in the bash shell. I added comments to the commit as well.

**Comment by eeide** [comment]
Argh! Fixed, I think. Thank you for reporting this.

**Comment by mpflanzer** [comment]
Yes, fixed. ;-)
