### ISSUE TITLE
C-reduce can't reduce this simple example

### ISSUE THREAD

**Issue by ptzafrir** [csmith-project/creduce#66]
After reducing a test case, I noticed C-reduce misses some simple transformations.
To demonstrate, the following code example:
```
//Filename is main.cpp
#ifndef SOMETHING
#include <iostream>
struct Nothing;
namespace some {
  template<typename T,typename F>
  class cls {
    public:
    static void foo(T a);
  };
}
#endif //SOMETHING
template <typename T,typename F>
void some::cls<T,F>::foo(T a) { std::cout<<a;}

void bar(const char * b) {
  some::cls<const char *,Nothing>::foo(b);
}

int main(int argc, char**argv) {
  bar("hello");
  return 0;
}
```
Test script
```
#!/bin/bash -e
g++ main.cpp -o run
./run | grep hello
```
Is reduced to:
```
#ifndef SOMETHING
#include <iostream>
template <typename T, typename> class A {
public:
  static void m_fn1(T);
};
#endif
template <typename T, typename F> void A<T, F>::m_fn1(T a) { std::cout << a; }

main() { A<char *, int>::m_fn1("hello"); }
```
* the #ifndef and #endif can be removed
* the class can be changed to struct
* typename F can be removed from the template
* the template could be replaced with the only instantation with the type \<char *\>

this would result in the reduced example:
```
#include <iostream>
main(){std::cout<<"hello";}
```

**Comment by regehr** [comment]
The failure to remove easy preprocessor stuff is somewhat expected-- we generally reduce preprocessed code, so have never focused on this problem. It's probably not too difficult to solve, perhaps as a new pass, if you have time to implement it @ptzafrir.

The rest of the issues are probably best resolved by seeing why clang_delta didn't remove them. I'm not sure if @chenyang78 has time for that these days.

**Comment by chenyang78** [comment]
Thanks for reporting the issue, @ptzafrir. 

I will try to get time to investigate these issues.

**Comment by ptzafrir** [comment]
Are there any improvements with those topics in the current trunk version?

**Comment by regehr** [comment]
Not that I know of.

**Comment by regehr** [comment]
I just pushed a change that does the class->struct change.

**Comment by regehr** [comment]
I know how to remove the preprocessor directives but it's not clear I'll be able to get to it during the next few weeks.

Only Yang can do the template manipulations.

**Comment by chenyang78** [comment]
I haven't done anything. Sorry about that!

**Comment by regehr** [comment]
I haven't looked at this particular test case but the CPP directives should be going away now.

**Comment by regehr** [comment]
Current output.

```
#include <iostream>
template <typename x0, typename> struct x1 { static void x2(x0); };
template <typename x0, typename x3> void x1<x0, x3>::x2(x0 x4) {
  std::cout << x4;
}
int main() { x1<char *, int>::x2("Hello"); }
```

**Comment by regehr** [comment]
Current output-- one more case left to handle.

```
#include <iostream>
template <typename x0> struct A { static void m_fn1(x0); };
template <typename x0> void A<x0>::m_fn1(x0 p1) { std::cout << p1; }
int main() { A<char *>::m_fn1("Hello"); }
```

**Comment by regehr** [comment]
Well this certainly took a while but with Yang's latest patch we produce this:

```
#include <iostream>
int main() { std::cout << "Hello"; }
```
