### ISSUE TITLE
The master is not usable

### ISSUE THREAD

**Issue by vgvassilev** [csmith-project/creduce#70]
I am trying to use creduce on Yosemite:

```
../src/configure --prefix=/Users/vvassilev/workspace/github/creduce/inst/ --with-llvm=/Users/vvassilev/workspace/github/creduce/dependencies/clang+llvm-3.7.0-x86_64-apple-darwin/ --enable-trans-assert TOPFORMFLAT=/Users/vvassilev/workspace/github/creduce/dependencies/delta-2006.08.03/
```

It builds fine then when I try the demo on your page it says:
```
./inst/bin/creduce --verbose ./test1.sh small.c 
successfully checked prereqs for pass_blank
successfully checked prereqs for pass_clang_binsrch
prereqs not found for pass pass_lines at ./inst/bin/creduce line 246.
```

I also tried to use creduce-2.3 with clang/llvm toolchain 3.6.2 and ran into the same sort of issues.

The dependencies (configure-wise) seem to be fine. Any ideas what might be wrong?

**Comment by vgvassilev** [comment]
Got it! I needed to build delta (run make in the delta folder). Perhaps it is better in configure to check for the actual binary located in TOPFORMFLAT instead of checking a folder.

**Comment by eeide** [comment]
I'm glad that you were able to resolve the problem you were having!
