### ISSUE TITLE
Directory-wide reduce [not-a-bug]

### ISSUE THREAD

**Issue by JIghtuse** [csmith-project/creduce#71]
Hi!
First of all, thanks for creduce! This tool helps me many times.
But there are some cases creduce can't handle. Let's suppose I have some IDE/File manager that crashes opening some directory. It would be great to reduce such directory to find relevant set of files (responsible for crash). Is there tool for this? How hard would it be to implement one? I would be glad to see some hints/posts on implementing it.
Sorry for some offtop.

**Comment by eeide** [comment]
I'm not familiar with a tool that does exactly the thing you are asking about. But it could be fun project to implement such a tool!

The name of C-Reduce's general technique is "delta debugging." If you google for this term, you can find several tools that use this general technique.

The general idea of delta debugging is a search procedure. At every "step," the search tries different things to make the current input "smaller" in some way, subject to a test that some interesting behavior is preserved (e.g., the IDE still crashes). Whenever a step succeeds, the new, smaller input becomes the current input, and the search proceeds. Whenever a step fails, the search "backs up" and tries a different way of making the input smaller. The search runs until the tool cannot find any way to make the current input smaller.

Most delta debuggers work by trying to make an input *file* smaller. For the situation you describe, you need a tool that makes *directories* "smaller." So in your tool, every search step would move some of the files out of the directory and then test to see if your IDE still crashes. If it does, great—you've taken a reduction step! If not, your tool would move the just-removed files back in, and try to remove some other set of the files.

As I said, this sounds like a fun programming project!

**Comment by eeide** [comment]
Also, we're very glad that you like C-Reduce! Thank you for letting us know.

**Comment by regehr** [comment]
Hi Boris, I agree with Eric that although C-Reduce isn't the tool you want for IDE crashes, a different tool based on delta debugging should work just fine.

One questions is how to get control of the circumstances leading up to the IDE crash. This is crucial. If the IDE loads everything out of a single directory then that's easy, but if it loads stuff from all over the place you might be forced to do something more drastic like using strace (or another syscall interposition layer) to learn the full set of files that it loads. Then, these files can be eliminated or reduced using a delta debugger as suggested by Eric. It could even be the case that C-Reduce would be useful for reducing some of these files.

**Comment by regehr** [comment]
I have C-Reduce reducing multiple files at once, in the multifile branch. It isn't tested very well yet. I'll merge it once I'm more sure that it works.

**Comment by regehr** [comment]
Multifile reduction seems to be working just fine (and is merged), closing.

**Comment by JIghtuse** [comment]
@regehr, oh, great! Thank you!
