### ISSUE TITLE
Can't run on files in subdirectory

### ISSUE THREAD

**Issue by jonashaag** [csmith-project/creduce#73]
This

```
creduce test.sh foo/bar.c
```

fails with some [`error in File::Copy::copy`](https://github.com/csmith-project/creduce/blob/7d70aa0c1cc814d83738c034dbd835dc1c6a1619/creduce/creduce.in#L236), while

```
cp foo/bar.c .
sed -i 's/foo\/bar.c/bar.c/g' test.sh
creduce test.sh bar.c
```

works.

**Comment by regehr** [comment]
Hi Jonas, I don't think this is a bug but rather we probably didn't document very well the assumptions made by the interestingness tests. Actually I was just working on this a few minutes ago -- could you take a look at the "creduce --help" information printed by the master branch? It gives a bit of detail about this.

**Comment by jonashaag** [comment]
It think it's not clear from the new help either. Maybe you should simply exit with an error if someone attempts to pass in a source file from a subdirectory (or creduce is invoked without any source file that has no path prefix)

**Comment by regehr** [comment]
You're right. I can't work on this right now but will comment here later once it's better.

**Comment by regehr** [comment]
Ok, I've unconfused creduce about file paths a bit, commands like this should work now, please test:

```
creduce test.sh foo/bar.c
```

**Comment by regehr** [comment]
Also I would appreciate feedback (cc @eeide) on the new --help output.

**Comment by eeide** [comment]
Noted. (I might not get to this for a little bit.)

**Comment by jonashaag** [comment]
Works for me, thank you!

**Comment by eeide** [comment]
I looked at the new --help output, and I like it a lot! It is excellent.

The only change I might make is to include the short commit hash in the version string at the top. Ala:

> creduce 2.5.0 (XXX) -- a C and C++ program reducer

I suppose this would go along with implementing --version, too.

**Comment by regehr** [comment]
Thanks Eric.

I know you know this is coming.... could you implement the commit hash thing?

**Comment by eeide** [comment]
Sure, will do this now.

**Comment by eeide** [comment]
`creduce --help` now says:

> creduce 2.5.0 (69f26b4) -- a C and C++ program reducer

**Comment by regehr** [comment]
Nice!
