### ISSUE TITLE
Copy propagation of a variable affects its own definition

### ISSUE THREAD

**Issue by UniQP** [csmith-project/creduce#78]
The file test.txt contains the line
b = a[b];
and the the copy propagation propagates b into its own definition, which leads to
b = a[a[b]];
b = a[a[a[a[b]]]];
b = a[a[a[a[a[a[a[a[b]]]]]]]];
and so on. (It eventually stop doing this but afterwards clang-format uses a lot of memory.)

The issue occurs with creduce-2.4.0. I also attached a check "script".

[test.txt](https://github.com/csmith-project/creduce/files/87438/test.txt)
[check.txt](https://github.com/csmith-project/creduce/files/87439/check.txt)

**Comment by regehr** [comment]
Looks like bug is still there in the current version.

```
$ ~/creduce-install/libexec/clang_delta --transformation=copy-propagation --counter=1 --output=- test.txt 
int a[1];
int b;

int main(void)
{
	b = a[a[b]];
}
```

**Comment by chenyang78** [comment]
Fixed. Thanks for reporting the issue, Sebastian!
