### ISSUE TITLE
Segmentation fault in transformation remove-unused-enum-member

### ISSUE THREAD

**Issue by UniQP** [csmith-project/creduce#79]
clang_delta --transformation=remove-unused-enum-member --counter=1 test.txt
Segmentation fault (core dumped)

[test.txt](https://github.com/csmith-project/creduce/files/95009/test.txt)

P.S. I used the multifile reduction for this test and it works great :-)

**Comment by chenyang78** [comment]
Fixed. Thanks, Sebastian!
