### ISSUE TITLE
Segmentation fault in transformation empty-struct-to-int

### ISSUE THREAD

**Issue by UniQP** [csmith-project/creduce#81]
clang_delta --transformation=empty-struct-to-int --counter=1 test.txt
Segmentation fault (core dumped)

[test.txt](https://github.com/csmith-project/creduce/files/112225/test.txt)

clang_delta --version
clang_delta 2.5.0
Git version: 7ebf7b8

**Comment by chenyang78** [comment]
Fixed. Thanks, Sebastian!
