### ISSUE TITLE
'pass_lines' pass doesn't check if bug is reproducable

### ISSUE THREAD

**Issue by JVApen** [csmith-project/creduce#88]
I'm trying to reproduce a bug in clang-tidy (trunk version), when I noticed that my test file is reduced to empty, while reduce.sh doesn't agree with this being a valid case.

I can reproduce this by running following command on the attached files
([reproduction.zip](https://github.com/csmith-project/creduce/files/160007/reproduction.zip))
:
creduce --no-default-passes --debug --add-pass pass_lines 0 1 reduce.sh t.cpp
The debug output can be found in debug.txt

If I afterwards run reduce.sh on the resulting (empty) t.cpp, it indicates that the bug is not reproducable.

I noticed this behavior both with the default  version on ubuntu 14.04 ( 2.2.1 ) as with trunk version (creduce 2.5.0 (a47dc02)).

If you need any more info, just let me know.

**Comment by regehr** [comment]
I'm trying to repro but on a handy Ubuntu 14.04 machine I can't build LLVM with libcxx, do the errors below ring any bells for you?

[1414/2644] Linking CXX shared library lib/libc++.so.1.0
FAILED: : && /home/regehr/clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang++  -fPIC  -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers  -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -std=c++11 -fcolor-diagnostics -ffunction-sections -fdata-sections -O3   -Wl,-z,defs  -fPIC -nodefaultlibs -shared -Wl,-soname,libc++.so.1 -o lib/libc++.so.1.0 projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/shared_mutex.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/regex.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/iostream.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/any.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/strstream.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/mutex.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/utility.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/memory.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/debug.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/string.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/hash.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/new.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/valarray.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/ios.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/bind.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/optional.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/future.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/stdexcept.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/chrono.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/thread.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/algorithm.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/typeinfo.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/locale.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/random.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/condition_variable.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/exception.cpp.o projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/system_error.cpp.o  -lpthread -lc -lm -lrt -lgcc_s -Wl,-rpath,"\$ORIGIN/../lib" && :
projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/iostream.cpp.o: In function `__clang_call_terminate':
../projects/libcxx/src/iostream.cpp:(.text.__clang_call_terminate[__clang_call_terminate]+0x2): undefined reference to `__cxa_begin_catch'
projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/iostream.cpp.o:(.data.rel.ro._ZTINSt3__110__stdinbufIcEE[_ZTINSt3__110__stdinbufIcEE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/iostream.cpp.o:(.data.rel.ro._ZTINSt3__110__stdinbufIwEE[_ZTINSt3__110__stdinbufIwEE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/iostream.cpp.o:(.data.rel.ro._ZTINSt3__111__stdoutbufIcEE[_ZTINSt3__111__stdoutbufIcEE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
projects/libcxx/lib/CMakeFiles/cxx.dir/__/src/iostream.cpp.o:(.data.rel.ro._ZTINSt3__111__stdoutbufIwEE[_ZTINSt3__111__stdoutbufIwEE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'

**Comment by JVApen** [comment]
I think it has to do with linking, though let me just give [my script](https://github.com/csmith-project/creduce/files/160251/llvm_get.sh.zip) which I use to checkout and configure
I guess you can reduce it as you don't need everything.

FYI: The bug I was trying to reproduce/reduce is https://llvm.org/bugs/show_bug.cgi?id=26855, so make sure you get a revision on which it is not yet fixed. (like 262782)

**Comment by regehr** [comment]
Ok finally I reproduced this. I see the same thing happening: C-Reduce nukes the file completely.

However, I also see that your interestingness test gives a zero exit code for the empty file:

```
regehr@hawking:/tmp/reduce/reduce$ wc t.cpp
0 0 0 t.cpp
regehr@hawking:/tmp/reduce/reduce$ ../reduce.sh
1 warning generated.
Reproduced
regehr@hawking:/tmp/reduce/reduce$ echo $?
0
regehr@hawking:/tmp/reduce/reduce$ 
```

Please check your code again and see if there's a bug hiding in it.

**Comment by JVApen** [comment]
I've checked once again, with an empty file:   Outfile doesn't contain match 1
echo $?  > 1
If I look at the out.txt generated, this stays empty, so I don't see a reason why this would result in 'Reproduced'

:/tmp/reduce/reduce$ cat t.cpp ; ../reduce.sh 
+ for remove in core out.txt t.o compile_commands.json.bak
+ '[' -f core ']'
+ for remove in core out.txt t.o compile_commands.json.bak
+ '[' -f out.txt ']'
+ for remove in core out.txt t.o compile_commands.json.bak
+ '[' -f t.o ']'
+ for remove in core out.txt t.o compile_commands.json.bak
+ '[' -f compile_commands.json.bak ']'
+ clang++ -c t.cpp -o t.o -w -g -O0 -pipe -m64 -Qunused-arguments -fPIC -pthread -I. -std=c++1y -fvisibility=hidden -fvisibility-inlines-hidden -fopenmp -stdlib=libc++
+ '[' 0 '!=' 0 ']'
+ '[' -f core ']'
+ '[' '!' -f t.o ']'
+ cp /tmp/reduce//compile_commands.json ./
++ pwd
+ sed -i.bak 's|/tmp/reduce/|/tmp/reduce/reduce/|g' compile_commands.json
+ clang-tidy '-checks=-*,clang-analyzer-alpha.unix.Stream' -extra-arg=-D__clang_tidy__ t.cpp
+ '[' 0 '!=' 0 ']'
+ '[' -f core ']'
+ grep -F --silent 'warning: Opened File never closed. Potential Resource leak [clang-analyzer-alpha.unix.Stream]' out.txt
+ '[' 1 '!=' 0 ']'
+ echo 'Outfile doesn'\''t contain match 1'
Outfile doesn't contain match 1
+ exit 1
:/tmp/reduce/reduce$

**Comment by regehr** [comment]
It looks to me like something in your script is breaking the rules by referring to t.cpp by something other than a relative path to the cwd. C-Reduce runs everything out of throwaway temp dirs, and your script must always look there. Anyway I do not see a C-Reduce bug here.
