### ISSUE TITLE
pass_clang :: remove-unused-function removes functions top-down instead of down to top

### ISSUE THREAD

**Issue by JVApen** [csmith-project/creduce#89]
When trying to reduce some code, I've noticed that the reduction 'pass_clang :: remove-unused-function' is removing functions from top to bottom instead of vise versa. Doing this the other way around looks more logical.

Consider a cpp file with first a class-definition with pure virtual functions, followed by an implementation of such function, with an override after it. If the script verifies that the cpp-file still can compile, this means that it will always fail when the pure-virtual call is removed, though it could succeed if this implementation is removed.

Result: After running this pass, you can run it a second time to get extra reduction (10% on the file I was looking at)

**Comment by regehr** [comment]
Thanks for the observation! We'd welcome a pull request.

**Comment by JVApen** [comment]
Sorry, I don't know enough perl to make any decent changes; so I've just duplicated the pass in my local checkout

**Comment by regehr** [comment]
If this could be fixed in Perl I'd do it, but alas it'll have to be fixed in C++.

In any case this issue will only make C-Reduce converge more slowly, it should not affect the final reduced program. C-Reduce repeats the entire pass sequence until it can't reduce the size by even one byte.

**Comment by JVApen** [comment]
@regehr That ain't the behavior that I was noticing, as the pure virtual calls only were removed after I ran the pass again. Though if that is indeed the intended behavior, I guess I'm gonna close this one as it would only improve the performence.
