### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by regehr** [csmith-project/creduce#96]
I'm getting a null ptr deref at RenameCXXMethod.cpp:568, it's easy enough to work around by checking for null but I don't want to ignorantly patch around a bug that needs to be fixed elsewhere.

```
Program received signal SIGSEGV, Segmentation fault.
RenameCXXMethod::handleOneMemberTemplateFunction (this=0x1d7aeb0, MD=0x1e014d0) at RenameCXXMethod.cpp:568
568	  unsigned int NumFuns = I->second;
(gdb) p I
$1 = {<llvm::DebugEpochBase::HandleBase> = {<No data fields>}, Ptr = 0x0, End = <optimized out>}
(gdb) 
```

**Comment by chenyang78** [comment]
John, do you have a test case for this issue? Thanks.

**Comment by regehr** [comment]
Argh I think I deleted it, but this came up often in a batch of reductions so I'll post one soon.
